language: java

services:
  - mysql
  - postgresql

jdk:
  - oraclejdk8

install:
  - mkdir -p download
  - test -f download/apache-cassandra-2.2.6-bin.tar.gz || wget http://www-eu.apache.org/dist/cassandra/2.2.6/apache-cassandra-2.2.6-bin.tar.gz -O download/apache-cassandra-2.2.6-bin.tar.gz
  - tar xzf download/apache-cassandra-2.2.6-bin.tar.gz
  - cp -f src/test/resources/cassandra.yaml apache-cassandra-2.2.6/conf
  - apache-cassandra-2.2.6/bin/cassandra
  - src/test/bash/install_vault.sh
  - src/test/bash/local_run_vault.sh &

before_script:
  - mysql -e "CREATE USER 'spring' IDENTIFIED by 'vault';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'spring'@'%' WITH GRANT OPTION;";
  - psql -U postgres -c "CREATE ROLE spring WITH LOGIN PASSWORD 'vault' CREATEROLE CREATEUSER;"
  - sleep 30 # wait until Cassandra is up
  - apache-cassandra-2.2.6/bin/cqlsh localhost -u cassandra -p cassandra -e "CREATE USER 'spring' WITH PASSWORD 'vault' SUPERUSER"

script: mvn clean verify

after_script:
  - apache-cassandra-2.2.6/bin/nodetool stopdaemon
  - pkill vault

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'